### PR TITLE
Feat/kv + routes 

### PR DESCRIPTION
**Pull request by thomas-mauran**
this pr has been coded by @sea-gull-diana [here](https://github.com/thomas-mauran/orka/pull/4)  

# What's this PR do ? 
This PR takes the `kv` implementation from @charley04310 's PR and uses it to implement routes `workloads` and `instances`
When scheduling an instance in the `POST instances` route, the program creates a thread where it follows the stream returned by the scheduler and saves updates to a `kv::Batch`, which is read and saved to the kv store every 5 seconds.

We are also now generating uuids for instances and send them to scheduler on instance creation. These uuids can be sent to scheduler later in order to stop or destroy instances.

## Other changes:
- Created a `KeyValueBatch` struct which has a `batch` property and implements `Defer` and `DerefMut` (hopefully correctly), thus allowing me to clear the batch after every update.
- Return instance id to client on instance creation.
- Add mutex for kv management
- Match status code

### CODE REVIEW

**Comment by thomas-mauran** [comment]
ping @sameo for a review

**Comment by sameo** [comment]
@charley04310 Any idea why the CI is not triggered with that PR?

**Comment by charley-geoffroy** [comment]
@sameo, I would say that this mainly comes from the fact that the CI is only implemented on push event. Would the workflow need updating like something like this ?

```
on:
  pull_request:
    paths:
      - "controller/**"
```

**Comment by sameo** [comment]
> @sameo, I would say that this mainly comes from the fact that the CI is only implemented on push event. Would the workflow need updating like something like this ?
> 
> ```
> on:
>   pull_request:
>     paths:
>       - "controller/**"
> ```

Ah yes, it should. Thanks!

**Comment by sameo** [comment]
All PRs should trigger the CI.

**Comment by sameo** [comment]
Please rebase this PR.

**Comment by thomas-mauran** [comment]
> Please rebase this PR.

Should be good now

**Comment by thomas-mauran** [comment]
ping @sameo for a review

**Pull request closed without merging**
